ALTER TABLE "posts" DROP CONSTRAINT IF EXISTS fk0_author;
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS fk0_post;
ALTER TABLE "comments" DROP CONSTRAINT IF EXISTS fk1_author;

DROP TABLE IF EXISTS "users";
DROP TABLE IF EXISTS "posts";
DROP TABLE IF EXISTS "comments";